server:
  port: 8083

spring:
  application:
    name: social-service
  datasource:
    url: jdbc:postgresql://localhost:5433/socials_db
    username: connecta
    password: connecta
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
